name: ingress-nginx

type: go

up:
  - podman
  - go:
      version: 1.21.5
      modules: true
  - custom:
      name: Create GeoIP directory
      met?: ls rootfs/geoip &> /dev/null
      meet: mkdir rootfs/geoip
  - custom:
      name: Configure GeoIP database files
      met?: ls rootfs/geoip/GeoLite2-Country.mmdb.gz &> /dev/null
      meet: gsutil cp gs://shopify-mmdb-free/GeoLite2-Country.mmdb.gz rootfs/geoip/
env:
  BASE_IMAGE: gcr.io/shopify-docker-images/apps/production/nginx:1.21.6.6
  RUNTIME: podman

commands:
  lint:
    desc: 'Run lua tests'
    run: build/run-in-docker.sh hack/verify-lualint.sh hack/verify-golint.sh
  test-lua:
    desc: 'Run lua tests'
    run: build/run-in-docker.sh make lua-test
  benchmark-plugin-lua: # can make more generic if other plugins add benchmarks
    desc: 'Run lua benchmarks'
    run: build/run-in-docker.sh ./rootfs/etc/nginx/lua/plugins/opentelemetry/benchmark/benchmark.sh
  test-go:
    desc: 'Run go tests'
    run: build/run-in-docker.sh make test
  e2e-test:
    desc: 'Run e2e tests'
    run: make kind-e2e-test
  static-check:
    desc: 'Run static checks'
    run: build/run-in-docker.sh make static-check
  server:
    desc: 'start nginx server'
    run: podman-compose -f shopify-localdev/podman-compose.yml up
