# Based on https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-network/ingress-nginx.yaml

containers:
  default:
    docker: gcr.io/shopify-docker-images/apps/ci/nginx-e2e-test-runner:db069d180fdab17f9bc5b57e124bff88e4842cc6
    workdir: /go/src/k8s.io/ingress-nginx

steps:
- label: Static Check
  timeout: 5m
  run:
  - make static-check
  env:
    GOMODCACHE: /go/src/${PKG}/.modcache

- label: Lua Unit Test
  timeout: 5m
  run:
  - make lua-test

- label: Go Unit Test
  timeout: 15m
  run:
  - PKG=k8s.io/ingress-nginx build/cover.sh
