# Based on https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-network/ingress-nginx.yaml

containers:
  default:
    docker: gcr.io/shopify-docker-images/apps/ci/nginx-e2e-test-runner:447fdf43e1b40a3754f3c7f9d64b5abaed27e629
    workdir: /go/src/k8s.io/ingress-nginx

steps:
- label: Static Check
  timeout: 10m
  run:
  - make static-check
  env:
    GOMODCACHE: /go/src/${PKG}/.modcache
    SHOPIFY_BUILD_MEMORY_LIMIT: 10g

- label: Lua Unit Test
  timeout: 5m
  env:
    STATSD_HOST: localhost
    STATSD_PORT: "8125"
  run:
  - make lua-test

- label: Go Unit Test
  timeout: 15m
  run:
  - PKG=k8s.io/ingress-nginx build/cover.sh
