# Based on https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-network/ingress-nginx.yaml

shared:
  e2e_defaults: &e2e_defaults
    timeout: 30m
    run: build/shopify/e2e.sh
    agents:
      queue: k8s-ci

containers:
  default:
    docker: quay.io/kubernetes-ingress-controller/e2e:v03062020-7b6e2dd31
    workdir: /go/src/k8s.io/ingress-nginx

steps:
- label: Static Check
  timeout: 5m
  run:
  - USE_DOCKER=false make static-check

- label: Lua Unit Test
  timeout: 5m
  run:
  - USE_DOCKER=false make lua-test

- label: Go Unit Test
  timeout: 15m
  run:
  - PKG=k8s.io/ingress-nginx build/cover.sh

- label: e2e (:kubernetes:v1.14-latest)
  <<: *e2e_defaults
  env:
    KUBERNETES_VERSION: v1.14-latest
