# Based on https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-network/ingress-nginx.yaml

containers:
  default:
    docker: gcr.io/shopify-docker-images/apps/ci/nginx-e2e-test-runner:f2ceec7c30dd13accbc36a4883f2488cbe84552c
    workdir: /go/src/k8s.io/ingress-nginx

steps:
- label: Static Check
  timeout: 10m
  run:
  - make static-check
  env:
    GOMODCACHE: /go/src/${PKG}/.modcache

- label: Lua Unit Test
  timeout: 5m
  env:
    STATSD_HOST: localhost
    STATSD_PORT: "8125"
  run:
  - make lua-test

- label: Go Unit Test
  timeout: 15m
  run:
  - PKG=k8s.io/ingress-nginx build/cover.sh
