# Based on https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-network/ingress-nginx.yaml

shared:
  e2e_defaults: &e2e_defaults
    timeout: 60m
    run: build/shopify/e2e.sh
    agents:
      queue: k8s-ci

containers:
  default:
    docker: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20210104-g81a8d5cd8
    workdir: /go/src/k8s.io/ingress-nginx

steps:
- label: Static Check
  timeout: 5m
  run:
  - make static-check

- label: Lua Unit Test
  timeout: 5m
  run:
  - make lua-test

- label: Go Unit Test
  timeout: 15m
  run:
  - PKG=k8s.io/ingress-nginx build/cover.sh

- label: e2e (:kubernetes:v1.16-latest)
  <<: *e2e_defaults
  env:
    KUBERNETES_VERSION: v1.16-latest

- label: e2e (:kubernetes:v1.17-latest)
  <<: *e2e_defaults
  env:
    KUBERNETES_VERSION: v1.17-latest

- label: e2e (:kubernetes:v1.18-latest)
  <<: *e2e_defaults
  env:
    KUBERNETES_VERSION: v1.18-latest
