# Based on https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-network/ingress-nginx.yaml

containers:
  default:
    docker: quay.io/kubernetes-ingress-controller/e2e:v06232019-5bb168152
    workdir: /go/src/k8s.io/ingress-nginx

steps:
- label: Static Check
  timeout: 5m
  run:
  - make static-check

- label: Lua Unit Test
  timeout: 5m
  run:
  - make lua-test

- label: Go Unit Test
  timeout: 15m
  run:
  - make cover
