# Based on https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-network/ingress-nginx.yaml

containers:
  default:
    docker: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20220110-gfd820db46
    workdir: /go/src/k8s.io/ingress-nginx

steps:
- label: Static Check
  timeout: 5m
  run:
  - make static-check
  env:
    GOMODCACHE: /go/src/${PKG}/.modcache

- label: Lua Unit Test
  timeout: 5m
  run:
  - make lua-test

- label: Go Unit Test
  timeout: 15m
  run:
  - PKG=k8s.io/ingress-nginx build/cover.sh
