containers:
  production:
    environment: production
    build:
      command: build/shopify/pipa-main.sh
      timeout: 40m

steps:
- build: production
- wait
- label: ':admission_tickets: Binary Authorization Checks'
  agents:
    queue: pipa-production
  command: pipa vouch
  timeout_in_minutes: 5
