containers:
  base_nginx:
    environment: production
    application: nginx
    dockerfile:
      dir: images/nginx/rootfs
      platform: linux/amd64,linux/arm64
      build_timeout: 400m
      tag_using_path: images/nginx/rootfs/VERSION
  e2e:
    environment: ci
    application: nginx-e2e-test-runner
    dockerfile:
      dir: images/test-runner/rootfs
      platform: linux/amd64,linux/arm64
      build_timeout: 60m
      build_args:
        BASE_IMAGE: gcr.io/shopify-docker-images/apps/production/nginx:0fa76b71c29e7dfade49be0b615ffa0fa666fddf
        GOLANG_VERSION: 1.21.5
        ETCD_VERSION: 3.4.3-0
        K8S_RELEASE: v1.26.0
        RESTY_CLI_VERSION: "0.27"
        RESTY_CLI_SHA: e5f4f3128af49ba5c4d039d0554e5ae91bbe05866f60eccfa96d3653274bff90
        LUAROCKS_VERSION: 3.8.0
        LUAROCKS_SHA: ab6612ca9ab87c6984871d2712d05525775e8b50172701a0a1cabddf76de2be7
        CHART_TESTING_VERSION: 3.8.0
        YAML_LINT_VERSION: 1.27.1
        YAMALE_VERSION: 4.0.4
        HELM_VERSION: 3.11.2
        GINKGO_VERSION: 2.9.5
        GOLINT_VERSION: latest
  production:
    environment: production
    dockerfile:
      platform: linux/amd64,linux/arm64
      build_timeout: 60m
      build_args:
        BASE_IMAGE: gcr.io/shopify-docker-images/apps/production/nginx:0fa76b71c29e7dfade49be0b615ffa0fa666fddf
        TARGETARCH: amd64
        VERSION: $SHOPIFY_BUILD_COMMIT
        COMMIT_SHA: $SHOPIFY_BUILD_COMMIT
        FREE_GEOIP_FILES: "GeoLite2-City.mmdb,GeoLite2-ASN.mmdb"
        PAID_GEOIP_FILES: "GeoIP2-City.mmdb,GeoIP2-ISP.mmdb,GeoIP2-Anonymous-IP.mmdb,GeoIP.dat"
        # GeoLite2-City and GeoLite2-ASN are required even if unused to keep the use-geoip2 configmap setting set to true
        # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-geoip2

steps:
- build: base_nginx
  key: base_build
- build: e2e
  depends_on: base_build
- build: production
  depends_on: base_build
