FROM gcr.io/shopify-docker-images/apps/ci/nginx-e2e-test-runner:02c4eeca604a507fb0e1f19707d5045c6e493316
# You can also build your own test runnner if you want


RUN apk add sudo vim
RUN luarocks install luabenchmark

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

RUN set -o vi

EXPOSE 443
WORKDIR /etc/nginx/lua

CMD ["nginx"]
